#include "system_monitor.hpp"
#include <arpa/inet.h>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <ifaddrs.h>
#include <net/if.h>
#include <pwd.h>
#include <sstream>
#include <sys/statvfs.h>
#include <unistd.h>
namespace epui::rpi {namespace {std::uint64_t steady_ms(){return static_cast<std::uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now().time_since_epoch()).count());}std::string run_command(const char* cmd){std::string out;if(FILE* p=::popen(cmd,"r")){char b[256];while(std::fgets(b,sizeof(b),p))out+=b;::pclose(p);}return out;}}
float SystemMonitor::read_float_file(const char* path,float scale){std::ifstream f(path);float v=-1;if(f>>v)return v*scale;return -1;}float SystemMonitor::vcgencmd_value(const char* command){const std::string s=run_command(command);const auto p=s.find('=');if(p==std::string::npos)return -1;char* end=nullptr;const float v=std::strtof(s.c_str()+p+1,&end);return end==s.c_str()+p+1?-1:v;}std::uint32_t SystemMonitor::vcgencmd_throttled(){const std::string s=run_command("vcgencmd get_throttled 2>/dev/null");const auto p=s.find("0x");return p==std::string::npos?0:static_cast<std::uint32_t>(std::strtoul(s.c_str()+p,nullptr,16));}
bool SystemMonitor::read_cpu(std::uint64_t& total,std::uint64_t& idle)const{std::ifstream f("/proc/stat");std::string cpu;std::uint64_t u,n,s,i,iw,irq,si,st;if(!(f>>cpu>>u>>n>>s>>i>>iw>>irq>>si>>st)||cpu!="cpu")return false;idle=i+iw;total=u+n+s+i+iw+irq+si+st;return true;}
bool SystemMonitor::read_network(const std::string& iface,std::uint64_t& rx,std::uint64_t& tx)const{std::ifstream f("/proc/net/dev");std::string line;while(std::getline(f,line)){auto colon=line.find(':');if(colon==std::string::npos)continue;std::string name=line.substr(0,colon);name.erase(0,name.find_first_not_of(" \t"));name.erase(name.find_last_not_of(" \t")+1);if(name!=iface)continue;std::istringstream ss(line.substr(colon+1));std::uint64_t a,b,c,d,e,g,h,j,k,l,m,n,o,p;if(ss>>rx>>a>>b>>c>>d>>e>>g>>h>>tx>>j>>k>>l>>m>>n>>o>>p)return true;}return false;}
StatusSnapshot SystemMonitor::sample(){StatusSnapshot s;s.temperature_c=read_float_file("/sys/class/thermal/thermal_zone0/temp",0.001f);std::uint64_t total=0,idle=0;if(read_cpu(total,idle)){if(prev_cpu_total_&&total>prev_cpu_total_){const auto dt=total-prev_cpu_total_,di=idle-prev_cpu_idle_;s.cpu_percent=100.0f*static_cast<float>(dt-di)/static_cast<float>(dt);}prev_cpu_total_=total;prev_cpu_idle_=idle;}std::ifstream mem("/proc/meminfo");std::string key,unit;std::uint64_t value,total_k=0,avail_k=0;while(mem>>key>>value>>unit){if(key=="MemTotal:")total_k=value;else if(key=="MemAvailable:")avail_k=value;}if(total_k)s.memory_percent=100.0f*static_cast<float>(total_k-avail_k)/static_cast<float>(total_k);struct statvfs st{};if(::statvfs("/",&st)==0&&st.f_blocks)s.disk_percent=100.0f*static_cast<float>(st.f_blocks-st.f_bavail)/static_cast<float>(st.f_blocks);char host[128]{};if(::gethostname(host,sizeof(host)-1)==0)s.hostname=host;if(passwd* pw=::getpwuid(::geteuid()))s.user=pw->pw_name;double loads[1]{};if(::getloadavg(loads,1)==1)s.load1=loads[0];s.uptime_s=static_cast<std::uint64_t>(read_float_file("/proc/uptime"));ifaddrs* addrs=nullptr;if(::getifaddrs(&addrs)==0){for(ifaddrs* p=addrs;p;p=p->ifa_next){if(!p->ifa_addr||p->ifa_addr->sa_family!=AF_INET||(p->ifa_flags&IFF_LOOPBACK)||!(p->ifa_flags&IFF_UP))continue;char ip[INET_ADDRSTRLEN]{};auto* sin=reinterpret_cast<sockaddr_in*>(p->ifa_addr);if(::inet_ntop(AF_INET,&sin->sin_addr,ip,sizeof(ip))){s.interface=p->ifa_name;s.ipv4=ip;break;}}::freeifaddrs(addrs);}std::uint64_t rx=0,tx=0;const auto ms=steady_ms();if(read_network(s.interface,rx,tx)){if(prev_net_ms_&&prev_iface_==s.interface&&ms>prev_net_ms_){const float sec=(ms-prev_net_ms_)/1000.0f;s.rx_kib_s=static_cast<float>(rx-prev_rx_)/1024.0f/sec;s.tx_kib_s=static_cast<float>(tx-prev_tx_)/1024.0f/sec;}prev_rx_=rx;prev_tx_=tx;prev_net_ms_=ms;prev_iface_=s.interface;}s.supply_voltage_v=vcgencmd_value("vcgencmd pmic_read_adc EXT5V_V 2>/dev/null");s.core_current_a=vcgencmd_value("vcgencmd pmic_read_adc VDD_CORE_A 2>/dev/null");s.throttled=vcgencmd_throttled();return s;}
}
