#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <cstdint>
#include "epui/canvas.hpp"
#include "epui/page.hpp"
#include "demo_pages.hpp"
using namespace epui;
namespace {
constexpr int kScale=7,kPad=24,kClientW=Canvas::Width*kScale+kPad*2,kClientH=Canvas::Height*kScale+kPad*2;
struct AppState{Canvas canvas;Ui ui;openoledui::demo::HomePage home;openoledui::demo::SensorPage sensors;openoledui::demo::AboutPage about;AppState(){ui.add_page(home);ui.add_page(sensors);ui.add_page(about);}}g_app;
std::uint32_t now_ms(){return static_cast<std::uint32_t>(GetTickCount64()&0xffffffffu);}void handle_key(WPARAM key){switch(key){case VK_RIGHT:case 'D':g_app.ui.handle(Key::Next,now_ms());break;case VK_LEFT:case 'A':g_app.ui.handle(Key::Prev,now_ms());break;case VK_RETURN:case VK_SPACE:g_app.ui.handle(Key::Select,now_ms());break;case VK_ESCAPE:g_app.ui.handle(Key::Back,now_ms());break;default:break;}}
void paint(HWND hwnd){PAINTSTRUCT ps{};HDC hdc=BeginPaint(hwnd,&ps);RECT client{};GetClientRect(hwnd,&client);HDC mem=CreateCompatibleDC(hdc);HBITMAP bitmap=CreateCompatibleBitmap(hdc,client.right,client.bottom);HGDIOBJ old=SelectObject(mem,bitmap);HBRUSH bg=CreateSolidBrush(RGB(19,21,24));FillRect(mem,&client,bg);DeleteObject(bg);g_app.ui.render(g_app.canvas,now_ms());RECT bezel{kPad-8,kPad-8,kPad+Canvas::Width*kScale+8,kPad+Canvas::Height*kScale+8};HBRUSH bb=CreateSolidBrush(RGB(6,7,8));FillRect(mem,&bezel,bb);DeleteObject(bb);HBRUSH pixel=CreateSolidBrush(RGB(229,242,255));const std::uint8_t* fb=g_app.canvas.data();for(int y=0;y<Canvas::Height;++y)for(int x=0;x<Canvas::Width;++x){const std::size_t i=static_cast<std::size_t>(x+(y/8)*Canvas::Width);if((fb[i]>>(y&7))&1u){RECT r{kPad+x*kScale,kPad+y*kScale,kPad+(x+1)*kScale,kPad+(y+1)*kScale};FillRect(mem,&r,pixel);}}DeleteObject(pixel);SetBkMode(mem,TRANSPARENT);SetTextColor(mem,RGB(165,173,184));const char* hint="Left/Right or A/D: page   Enter: select   Esc: back";TextOutA(mem,kPad,kClientH-16,hint,lstrlenA(hint));BitBlt(hdc,0,0,client.right,client.bottom,mem,0,0,SRCCOPY);SelectObject(mem,old);DeleteObject(bitmap);DeleteDC(mem);EndPaint(hwnd,&ps);}
LRESULT CALLBACK proc(HWND hwnd,UINT msg,WPARAM wp,LPARAM lp){switch(msg){case WM_CREATE:SetTimer(hwnd,1,16,nullptr);return 0;case WM_TIMER:InvalidateRect(hwnd,nullptr,FALSE);return 0;case WM_KEYDOWN:handle_key(wp);InvalidateRect(hwnd,nullptr,FALSE);return 0;case WM_PAINT:paint(hwnd);return 0;case WM_DESTROY:KillTimer(hwnd,1);PostQuitMessage(0);return 0;default:return DefWindowProc(hwnd,msg,wp,lp);}}
}
int WINAPI WinMain(HINSTANCE instance,HINSTANCE,LPSTR,int show){const char* klass="EmbedPluginUISimulator";WNDCLASSA wc{};wc.lpfnWndProc=proc;wc.hInstance=instance;wc.lpszClassName=klass;wc.hCursor=LoadCursor(nullptr,IDC_ARROW);if(!RegisterClassA(&wc))return 1;RECT r{0,0,kClientW,kClientH};AdjustWindowRect(&r,WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_MINIMIZEBOX,FALSE);HWND hwnd=CreateWindowExA(0,klass,"EmbedPluginUI - 128x64 Simulator",WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_MINIMIZEBOX,CW_USEDEFAULT,CW_USEDEFAULT,r.right-r.left,r.bottom-r.top,nullptr,nullptr,instance,nullptr);if(!hwnd)return 2;ShowWindow(hwnd,show);UpdateWindow(hwnd);MSG msg{};while(GetMessage(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessage(&msg);}return static_cast<int>(msg.wParam);}
